import { supabase } from './supabase';

export interface CloudinaryUploadResponse {
  secure_url: string;
  public_id: string;
  format: string;
  width: number;
  height: number;
}

/**
 * Uploads an image to Cloudinary using a secure signed request generated by Supabase Edge Function
 */
export const uploadImageToCloudinary = async (
  imageUri: string
): Promise<CloudinaryUploadResponse> => {
  // 1. Fetch Cloudinary signature from Edge Function
  const { data: sigData, error: sigError } = await supabase.functions.invoke(
    'create-cloudinary-signature',
    {
      method: 'POST',
    }
  );

  if (sigError || !sigData) {
    throw new Error(
      `Failed to obtain Cloudinary signature: ${sigError?.message || 'Unknown error'}`
    );
  }

  const { signature, timestamp, apiKey, cloudName, uploadPreset, folder } =
    sigData;

  // 2. Prepare Form Data
  const formData = new FormData();
  const filename = imageUri.split('/').pop() || 'waste_capture.jpg';
  const match = /\.(\w+)$/.exec(filename);
  const type = match ? `image/${match[1]}` : 'image/jpeg';

  // @ts-ignore RN FormData file format
  formData.append('file', {
    uri: imageUri,
    name: filename,
    type,
  });

  formData.append('api_key', apiKey);
  formData.append('timestamp', timestamp.toString());
  formData.append('signature', signature);
  formData.append('upload_preset', uploadPreset);
  formData.append('folder', folder);

  // 3. Post to Cloudinary direct API
  const uploadUrl = `https://api.cloudinary.com/v1_1/${cloudName}/image/upload`;
  const response = await fetch(uploadUrl, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Cloudinary upload failed (${response.status}): ${errorText}`);
  }

  const result: CloudinaryUploadResponse = await response.json();
  return result;
};
